"""empty message

Revision ID: 00baba4c1caa
Revises: 4736a5d8bbe3
Create Date: 2026-03-05 16:22:35.451056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00baba4c1caa'
down_revision = '4736a5d8bbe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('workspace_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('workspace_user_id_fkey'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
