"""empty message

Revision ID: 1e9447a3332a
Revises: f2f7ffa4586c
Create Date: 2026-03-04 22:07:16.142132

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1e9447a3332a'
down_revision = 'f2f7ffa4586c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('colors')
    with op.batch_alter_table('picture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orientation', sa.Enum('LANDSCAPE', 'PORTRAIT', 'SQUARE', name='format_enum'), nullable=False))
        batch_op.drop_column('tagsCustom')
        batch_op.drop_column('tagsSystem')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tagsSystem', postgresql.ARRAY(sa.BIGINT()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('tagsCustom', postgresql.ARRAY(sa.BIGINT()), autoincrement=False, nullable=False))
        batch_op.drop_column('orientation')

    op.create_table('colors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('hex_code', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('rgb_r', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rgb_g', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rgb_b', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('colors_pkey')),
    sa.UniqueConstraint('name', name=op.f('colors_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
