"""empty message

Revision ID: 5a4fa927a01e
Revises: f8a0bbd2616a
Create Date: 2026-03-04 10:48:07.846042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a4fa927a01e'
down_revision = 'f8a0bbd2616a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orientation', sa.Enum('LANDSCAPE', 'PORTRAIT', 'SQUARE', name='format_enum'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picture', schema=None) as batch_op:
        batch_op.drop_column('orientation')

    # ### end Alembic commands ###
