"""empty message

Revision ID: 83ca57ad3003
Revises: 1e9447a3332a
Create Date: 2026-03-05 15:54:32.028875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83ca57ad3003'
down_revision = '1e9447a3332a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datasource_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'datasource', ['datasource_id'], ['id'])
        batch_op.drop_column('sources')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sources', sa.BIGINT(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('datasource_id')

    # ### end Alembic commands ###
