"""empty message

Revision ID: 969895c21ef2
Revises: d57fdc1f31f9
Create Date: 2026-03-03 17:45:41.321691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '969895c21ef2'
down_revision = 'd57fdc1f31f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picture', schema=None) as batch_op:
        batch_op.alter_column('google_id',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=510),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picture', schema=None) as batch_op:
        batch_op.alter_column('google_id',
               existing_type=sa.String(length=510),
               type_=sa.BIGINT(),
               existing_nullable=False)

    # ### end Alembic commands ###
