"""empty message

Revision ID: c2e4aed0deca
Revises: 5a4fa927a01e
Create Date: 2026-03-04 20:58:03.124154

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c2e4aed0deca'
down_revision = '5a4fa927a01e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('colors')
    with op.batch_alter_table('picture', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', postgresql.ARRAY(sa.BIGINT()), autoincrement=False, nullable=False))

    op.create_table('colors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('hex_code', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('rgb_r', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rgb_g', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rgb_b', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('colors_pkey')),
    sa.UniqueConstraint('name', name=op.f('colors_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
