"""empty message

Revision ID: c6484f9809ef
Revises: a5e29873cab8
Create Date: 2026-03-05 19:13:29.400585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6484f9809ef'
down_revision = 'a5e29873cab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folder', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('folder_parent_folder_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'folder', ['parent_folder_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folder', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('folder_parent_folder_id_fkey'), 'folder', ['parent_folder_id'], ['id'])

    # ### end Alembic commands ###
