"""empty message

Revision ID: d57fdc1f31f9
Revises: db605da0f938
Create Date: 2026-03-03 15:55:14.614162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd57fdc1f31f9'
down_revision = 'db605da0f938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('picture')
    op.drop_table('users')
    op.drop_table('colors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('hex_code', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('rgb_r', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rgb_g', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rgb_b', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('colors_pkey')),
    sa.UniqueConstraint('name', name=op.f('colors_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_login_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('picture',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tagsSystem', postgresql.ARRAY(sa.BIGINT()), autoincrement=False, nullable=False),
    sa.Column('tagsCustom', postgresql.ARRAY(sa.BIGINT()), autoincrement=False, nullable=False),
    sa.Column('mainColors', postgresql.ARRAY(sa.VARCHAR(length=6)), autoincrement=False, nullable=False),
    sa.Column('ratio', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('resolutionX', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('resolutionY', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('contrast', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('luminosity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hasTest', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('isOutside', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('downloadLink', sa.VARCHAR(length=510), autoincrement=False, nullable=False),
    sa.Column('lastUpdated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('sources', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('picture_pkey'))
    )
    # ### end Alembic commands ###
