"""empty message

Revision ID: e9ace8312781
Revises: c6484f9809ef
Create Date: 2026-03-08 19:33:52.358947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9ace8312781'
down_revision = 'c6484f9809ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imageLocation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imageLocation',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('folderId', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('imageId', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('imageLocation_pkey'))
    )
    # ### end Alembic commands ###
