"""empty message

Revision ID: f2f7ffa4586c
Revises: 969895c21ef2
Create Date: 2026-03-04 09:37:55.594464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2f7ffa4586c'
down_revision = '969895c21ef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.String(length=510), nullable=True))
        batch_op.add_column(sa.Column('thumbnailLink', sa.String(length=510), nullable=False))
        batch_op.drop_column('hasTest')
        batch_op.drop_column('isOutside')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isOutside', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('hasTest', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('thumbnailLink')
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
