"""empty message

Revision ID: f8a0bbd2616a
Revises: f2f7ffa4586c
Create Date: 2026-03-04 10:00:28.718025

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f8a0bbd2616a'
down_revision = 'f2f7ffa4586c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.ARRAY(sa.BigInteger()), nullable=False))
        batch_op.drop_column('tagsSystem')
        batch_op.drop_column('tagsCustom')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tagsCustom', postgresql.ARRAY(sa.BIGINT()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('tagsSystem', postgresql.ARRAY(sa.BIGINT()), autoincrement=False, nullable=False))
        batch_op.drop_column('tags')

    # ### end Alembic commands ###
